services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 8080:11434
    volumes:
      - ./data/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:dev # fixed auth bug (linux)
    # image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    ports:
      - 80:8080
    volumes:
      - ./data/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URLS=http://host.docker.internal:8080
      - ENV=dev
      - WEBUI_AUTH=False
    extra_hosts:
      - host.docker.internal:host-gateway
